server:
  port: 8080

spring:
  datasource:
    username: root
    password: "!234567A!!ghj"
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

bot:
  userAgent: VitSearchBot
  referrer: https://ya.ru/
  timeout: 30000

indexing-settings:
  sites:
    - url: https://volochek.life/
      name: Вышний Волочёк
    - url: https://www.svetlovka.ru/
      name: Светловка
    - url: https://www.playback.ru/
      name: PlayBack.Ru


#    - url: https://www.lenta.ru/
#      name: Лента.ру
#    - url: https://skillbox.ru/
#      name: Skillbox
#    - url: https://nikoartgallery.com/
#      name: Niko
#    - url: https://et-cetera.ru/mobile/
#      name: Театр
